# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/apps/blog-cms'
    schedule:
      interval: 'weekly'
    target-branch: "develop"
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 20
  - package-ecosystem: 'npm'
    directory: '/apps/blog-service'
    schedule:
      interval: 'weekly'
    target-branch: "develop"
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 20
  - package-ecosystem: 'npm'
    directory: '/apps/blog-web'
    schedule:
      interval: 'weekly'
    target-branch: "develop"
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 20
  - package-ecosystem: 'npm'
    directory: '/apps/uploader-service'
    schedule:
      interval: 'weekly'
    target-branch: "develop"
    commit-message:
      prefix: 'deps'
    open-pull-requests-limit: 20