name: "@shared/{{SUB_APP}}"

on:
  push:
    paths:
      - "libs/{{SUB_APP}}/**"
    branches: 
      - "**"
  pull_request:
    paths:
      - "libs/{{SUB_APP}}/**"
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2

      - name: Install rush.js globally
        run: pnpm add @microsoft/rush --global

      - name: Install dependencies
        run: rush update --bypass-policy

      - name: Pre compilation
        run: rush build -o @shared/{{SUB_APP}}

      - name: Size Limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.TOKEN_FOR_SIZE_LIMIT_ACTION }}

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Testing Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Testing Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

  