name: blog-cms

on:
  push:
    paths:
      - 'apps/blog-cms/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'apps/blog-cms/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install rush.js globally
        run: pnpm add @microsoft/rush --global

      - name: Install dependencies
        run: rush update --bypass-policy

      - name: Pre compilation
        run: rush build -o blog-cms --impacted-by @shared/utils
        continue-on-error: true

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Testing Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Testing Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

  deployment:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x

      - name: Install rush.js globally
        run: pnpm add @microsoft/rush --global

      - name: Install dependencies
        run: rush update --bypass-policy

      - name: Compilation
        run: rush build -o blog-cms --impacted-by @shared/utils
        continue-on-error: true

      - name: List build directory
        run: ls -al apps/blog-cms/build/

      - name: Prepare files for deployment
        run: |
          mkdir -p build
          cp -r apps/blog-cms/build/* build/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: 'build/*'
          target: '/var/www/beg-monorepo/apps/blog-cms'
          overwrite: true

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Deployment Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Deployment Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'
