name: cms

on:
  push:
    paths:
      - 'apps/cms/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'apps/cms/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          mkdir -p ./apps/cms
          echo "VITE_BEG_SERVICE_DOMAIN=${{ vars.VITE_BEG_SERVICE_DOMAIN }}" >> ./apps/cms/.env
          echo "VITE_UPLOADER_SERVICE_DOMAIN=${{ vars.VITE_UPLOADER_SERVICE_DOMAIN }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_APPLICATION_ID=${{ vars.VITE_ALGOLIA_APPLICATION_ID }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_ADMIN_API_KEY=${{ vars.VITE_ALGOLIA_ADMIN_API_KEY }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_SEARCH_INDEX=${{ vars.VITE_ALGOLIA_SEARCH_INDEX }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_REALM=${{ vars.VITE_KEY_CLOAK_REALM }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_URL=${{ vars.VITE_KEY_CLOAK_URL }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_CLIENT_ID=${{ vars.VITE_KEY_CLOAK_CLIENT_ID }}" >> ./apps/cms/.env

      - name: Compilation
        run: pnpm run build --filter cms

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Testing Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Testing Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

  deployment:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          mkdir -p ./apps/cms
          echo "VITE_BEG_SERVICE_DOMAIN=${{ vars.VITE_BEG_SERVICE_DOMAIN }}" >> ./apps/cms/.env
          echo "VITE_UPLOADER_SERVICE_DOMAIN=${{ vars.VITE_UPLOADER_SERVICE_DOMAIN }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_APPLICATION_ID=${{ vars.VITE_ALGOLIA_APPLICATION_ID }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_ADMIN_API_KEY=${{ vars.VITE_ALGOLIA_ADMIN_API_KEY }}" >> ./apps/cms/.env
          echo "VITE_ALGOLIA_SEARCH_INDEX=${{ vars.VITE_ALGOLIA_SEARCH_INDEX }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_REALM=${{ vars.VITE_KEY_CLOAK_REALM }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_URL=${{ vars.VITE_KEY_CLOAK_URL }}" >> ./apps/cms/.env
          echo "VITE_KEY_CLOAK_CLIENT_ID=${{ vars.VITE_KEY_CLOAK_CLIENT_ID }}" >> ./apps/cms/.env

      - name: Compilation
        run: pnpm run build --filter cms

      - name: Prepare files for deployment
        run: |
          mkdir -p dist
          cp -r apps/cms/dist/* dist/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: 'dist/*'
          target: '/srv/beg-monorepo/apps/cms'
          overwrite: true

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Deployment Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Deployment Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'
