name: '@repo/eslint-config'

on:
  push:
    paths:
      - 'packages/eslint-config/**'
    branches:
      - '**'
  pull_request:
    paths:
      - 'packages/eslint-config/**'
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Pre compilation
        run: pnpm run build --filter @repo/eslint-config

      - name: Size Limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.TOKEN_FOR_SIZE_LIMIT_ACTION }}

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Testing Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Testing Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: 'Powered by Yancey Inc. and its affiliates.'
